dist: xenial
language: php
php:
  - 7.4snapshot
cache:
  directories:
    - ./vendor/
install:
  - travis_retry composer install --no-interaction --no-suggest --prefer-source
script:
  - composer run tests
  - ./vendor/bin/php-coveralls
matrix:
  fast_finish: true
